sudo: required
language: ruby
cache: bundler
before_install:
 - bundle -v
install:
 - sudo mkdir /etc/puppetlabs
 - sudo chmod a+rwx /etc/puppetlabs
 - bundle install
script:
  - 'bundle exec r10k deploy environment'
rvm:
  - 2.4
notifications:
  email: true
  irc:
    channels:
      - "irc.msi.umn.edu#puppet"
    on_success: change
    on_failure: always
    skip_join: true
